defmodule CalleeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :callee

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_callee_key",
    signing_salt: "luUzoYoo",
    same_site: "Lax",
    # Persistent login (also survives the Android app being killed). Browsers
    # cap cookie lifetime at ~400 days; Auth.fetch_current renews it daily.
    max_age: 400 * 86_400
  ]

  # Generous timeout: the Android app's background service heartbeats via
  # Doze-safe alarms (every few minutes while the phone sleeps).
  socket "/socket", CalleeWeb.UserSocket,
    websocket: [timeout: 15 * 60_000],
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :callee,
    gzip: not code_reloading?,
    only: CalleeWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :callee
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, {:multipart, length: 200_000_000}, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug CalleeWeb.Router
end
